name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
            arch: x64
            base_name: windows-x86_64
          - os: macos-15
            arch: armv8
            base_name: macos-armv8

    runs-on: ${{ matrix.os }}

    env:
      gst_version: 1.26.8

    steps:
      - uses: actions/checkout@v5

      - name: Setup Compiler (Windows)
        if: matrix.os == 'windows-2022'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Compiler (macOS)
        if: matrix.os == 'macos-15'
        run: |
          echo "CC=$(brew --prefix llvm@18)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@18)/bin/clang++" >> $GITHUB_ENV

      - name: Install build tools
        run: pipx install cmake conan ninja

      - name: Install pkg-config (Windows)
        if: matrix.os == 'windows-2022'
        run: choco install pkgconfiglite

      - name: Install conan profile
        run: conan config install .github/conan_profiles/${{ matrix.os }}-${{ matrix.arch }} -tf profiles

      - name: Cache conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ matrix.base_name }}-conan-${{ hashFiles('conanfile.py') }}
          restore-keys: ${{ matrix.base_name }}-conan-

      - name: Cache gstreamer
        id: cache-gstreamer
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/gstreamer
          key: ${{ matrix.base_name }}-gstreamer-${{ env.gst_version }}
          restore-keys: ${{ matrix.base_name }}-gstreamer

      - name: Download gstreamer
        if: steps.cache-gstreamer.outputs.cache-hit != 'true'
        env:
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
        shell: bash
        run: |
          gst_archive=${{ matrix.base_name }}-${{ env.gst_version }}.zip

          curl -o "$gst_archive" \
            "https://${space_name}.${space_region}.digitaloceanspaces.com/gstreamer/$gst_archive"

          7z x "$gst_archive" -o"${{ runner.temp }}" -y

      # - name: Configure SSH agent
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # xdaqmetadata

      # - name: Add GitHub to known hosts (Windows)
      #   if: matrix.os == 'windows-2022'
      #   shell: bash
      #   run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # - name: Clone xdaqmetadata
      #   shell: bash
      #   run: git clone -b dev --single-branch git@github.com:kontex-neuro/xdaqmetadata.git

      - name: Clone conan index
        run: git clone --depth 1 --branch master https://github.com/kontex-neuro/kontex-conan.git

      - name: Install xdaqmetadata (Windows)
        if: matrix.os == 'windows-2022'
        working-directory: kontex-conan
        run: conan create recipes/xdaqmetadata/0.1.1 -s os="Windows" -s arch="${{ matrix.arch }}" -s build_type="Release"

      - name: Install xdaqmetadata (macOS)
        if: matrix.os == 'macos-15'
        working-directory: kontex-conan
        run: conan create recipes/xdaqmetadata/0.1.1 -s os="Macos" -s arch="${{ matrix.arch }}" -s build_type="Release"

      - name: Build & Install
        env:
          PKG_CONFIG_PATH: ${{ runner.temp }}/gstreamer/lib/pkgconfig
        run: |
          conan install . -b missing -pr:a ${{ matrix.os }}-${{ matrix.arch }} -s build_type=Release
          cmake -S . -B build/Release --preset conan-release -G "Ninja" -DCMAKE_INSTALL_PREFIX=build/install -DCMAKE_BUILD_TYPE=Release
          cmake --build build/Release --target install 

      - name: Get & Set version
        shell: bash
        run: |
          version=$(conan inspect -f json . | jq -r '.version')
          echo $version
          echo "version=$version" >> $GITHUB_ENV

      - name: Zip
        shell: bash
        run: |
          mv build/install ${{ matrix.base_name }}
          7z a ${{ matrix.base_name }}-${{ env.version }}.zip ${{ matrix.base_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.base_name }}
          path: ${{ matrix.base_name }}-${{ env.version }}.zip