name: build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
            arch: x64
            base_name: windows-x86_64
          - os: macos-15
            arch: arm64
            base_name: macos-arm64

    runs-on: ${{ matrix.os }}

    env:
      gst_version: 1.26

    steps:
      - uses: actions/checkout@v5

      - name: Install build tools
        run: pipx install cmake conan ninja

      - name: Install conan profile
        run: conan config install .github/conan_profiles/${{ matrix.os }}-${{ matrix.arch }} -tf profiles

      - name: Cache conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ matrix.base_name }}-conan-${{ hashFiles('conanfile.py') }}
          restore-keys: ${{ matrix.base_name }}-conan-

      - name: Cache gstreamer
        id: cache-gstreamer
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/gstreamer
          key: ${{ matrix.base_name }}-gstreamer-${{ env.gst_version }}
          restore-keys: ${{ matrix.base_name }}-gstreamer

      - name: Download gstreamer
        if: steps.cache-gstreamer.outputs.cache-hit != 'true'
        env:
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
        shell: bash
        run: |
          gst_archive=${{ matrix.base_name }}-${{ env.gst_version }}.zip

          curl -o "$gst_archive" \
            "https://${space_name}.${space_region}.digitaloceanspaces.com/gstreamer/$gst_archive"

          7z x "$gst_archive" -o"${{ runner.temp }}" -y

      - name: Configure SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # xdaqmetadata

      - name: Add GitHub to known hosts (Windows)
        if: matrix.os == 'windows-2022'
        run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Clone xdaqmetadata
        run: git clone -b dev --single-branch git@github.com:kontex-neuro/xdaqmetadata.git

      - name: Install xdaqmetadata
        working-directory: xdaqmetadata
        env:
          PKG_CONFIG_PATH: ${{ runner.temp }}/gstreamer/lib/pkgconfig
        run: |
          conan install . -b missing -pr:a ${{ matrix.os }}-${{ matrix.arch }} -s build_type=Release
          cmake -S . -B build/Release --preset conan-release -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          cmake --build build/Release
          conan export-pkg . -pr:a ${{ matrix.os }}-${{ matrix.arch }} -s build_type=Release

      - name: Build
        env:
          PKG_CONFIG_PATH: ${{ runner.temp }}/gstreamer/lib/pkgconfig
        run: |
          conan install . -b missing -pr:a ${{ matrix.os }}-${{ matrix.arch }} -s build_type=Release
          cmake -S . -B build/Release --preset conan-release -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          cmake --build build/Release
