name: Test server on reboot

on:
  workflow_dispatch:

jobs:
  reboot-macos:
    runs-on: [self-hosted, macos]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test server on reboot
        run: $HOME/reboot-remote.sh
