name: Test server

on:
  workflow_dispatch:

jobs:
  reboot:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Reboot
        run: |
          env
          # ./reboot-remote.sh
