name: Test server on reboot

on:
  workflow_dispatch:

jobs:
  reboot:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test server on reboot
        run: $HOME/reboot-remote.sh
